server:
  port: 18081
# 应用名称
spring:
  application:
    name: demo

# 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
    username: root
    password: 123456

#sawgger 配置




